version: 2.1

# Shared workspace for passing env variables between jobs
defaults: &defaults
  working_directory: /tmp/ci-test

# Build executor is used for making the arm64 clamav zip, version-check is to compare latest version before make zip
executors:
  build:
    #resource_class: arm.medium
    machine:
      image: ubuntu-2004:current

  version-check:
    docker:
      - image: amazonlinux:2

# Setup for assume role with open ID and running CLI commands
orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  # Check latest version and pass env var to workspace
  check-latest-version:
    <<: *defaults
    executor: version-check
    steps:
      - run: mkdir -p workspace
      - run: |
          yum update -y
          yum install tar -y && yum install gzip -y
          yum makecache fast
          LATEST=$(yum info clamav-update | grep Version | awk -F':' '{ print $2 }' | tail -n1 | tr -d '[:space:]')
          echo "CLAMAV_LATEST=$LATEST" >> workspace/clamav-latest
          chmod 755 workspace/clamav-latest

      - persist_to_workspace:
          root: workspace
          paths:
            - clamav-latest
  build:
    <<: *defaults
    executor: build
    environment:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/ci-test/workspace
      - run: cat workspace/clamav-latest >> $BASH_ENV
      - aws-cli/setup:
          role-arn: $CIRCLECI_ROLE_ARN
      - run:
          name: "Verify clamav version"
          command: |
           echo "Building $CLAMAV_LATEST"
           #BUILD=1
           #aws s3 ls s3://$S3_BUCKET/lambda-$CLAMAV_LATEST.zip
           #if [[ $? == 0 ]]; then
           #   echo "File 'lambda-$CLAMAV_LATEST.zip' exists, exiting"
           #   echo "BUILD=0" >> $BASH_ENV
           #else
           #   echo "File for '$CLAMAV_LATEST' doesn't exists, building"
           #   echo "BUILD=1" >> $BASH_ENV
           #fi
      - run:
          name: "make zip"
          command: |
            #if [[ $BUILD == 1 ]]; then
              make all
            #fi
      - run:
          name: copy zip file
          command: |
            . ./workspace/clamav-latest
            . ./clamav-latest
            
            #if [[ $BUILD == 1 ]]; then
              aws s3 cp ./build/lambda.zip s3://$S3_BUCKET/pkg/lambda-${CLAMAV_LATEST}.zip
            #fi

workflows:
  version: 2
  make-sync-zip:
    jobs:
      - check-latest-version
      - build:
          context:
            - AWS
          requires:
            - check-latest-version
